---
- apt: name={{ item }} state=present
  with_items:
    - postgresql
    - redis-server

# create new user to run everything in a user's premission 
- group: name={{wye_user}} state=present
- user: name={{wye_user}} state=present group={{wye_user}} groups=postgres
- file: path=/srv/wye owner={{ wye_user }} state=directory

- name: clone the project
  git: repo={{wye_repo}} version=master dest=/srv/wye accept_hostkey=true depth=1
  sudo: true

- pip: name={{ item }} state=present
  with_items: ['psycopg2', 'virtualenv']

- shell: virtualenv /srv/.venv
- pip: virtualenv=/srv/.venv/ requirements=/srv/wye/requirements.txt

- postgresql_db: login_user=postgres name={{wye_db}} encoding='UTF-8' lc_collate='en_US.utf8' lc_ctype='en_US.utf8'
  sudo_user: postgres

- postgresql_user: db={{wye_db}} name={{wye_db_user}} password={{wye_db_pass}}
  sudo_user: postgres

- template: src=settings.py.j2 dest=/srv/wye/settings/prod.py  owner={{wye_user}} group={{wye_user}} mode=0644

- shell: /srv/.venv/bin/python /srv/wye/manage.py migrate

- shell: /srv/.venv/bin/python /srv/wye/manage.py collectstatic --noinput
  #notify: restart wye_uwsgi
  notify: restart nginx

- template: src=wye_nginx.conf.j2 dest=/etc/nginx/sites-enabled/wye.conf

- template: src=wye_upstart.conf.j2 dest=/etc/init/wye_uwsgi.conf

- name: restart wye_uwsgi
  service: name=wye_uwsgi state=restarted

- name: reload wye_uwsgi
  service: name=wye_uwsgi state=reloaded
